version: '3'

services: 
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=eduzz
      - POSTGRESQL_PASSWORD=eduzz
      - POSTGRESQL_DATABASE=api_eduzz